/**
 * Metrics Module
 * OpenTelemetry metrics for ADK operations
 */

import type { Counter, Histogram, MetricOptions } from "@opentelemetry/api";
import { type Meter, metrics } from "@opentelemetry/api";
import { METRICS } from "./constants";
import type {
	AgentMetricDimensions,
	LlmMetricDimensions,
	ToolMetricDimensions,
} from "./types";

/**
 * Metrics service for recording ADK operations
 */
export class MetricsService {
	private meter: Meter | null = null;

	// Counters
	private agentInvocationsCounter: Counter | null = null;
	private toolExecutionsCounter: Counter | null = null;
	private llmCallsCounter: Counter | null = null;
	private errorsCounter: Counter | null = null;

	// Histograms
	private agentDurationHistogram: Histogram | null = null;
	private toolDurationHistogram: Histogram | null = null;
	private llmDurationHistogram: Histogram | null = null;
	private llmTokensHistogram: Histogram | null = null;
	private llmInputTokensHistogram: Histogram | null = null;
	private llmOutputTokensHistogram: Histogram | null = null;

	/**
	 * Initialize metrics with the provided meter
	 */
	initialize(meterName: string, version: string): void {
		this.meter = metrics.getMeter(meterName, version);
		this.createMetrics();
	}

	/**
	 * Check if metrics are initialized
	 */
	get initialized(): boolean {
		return this.meter !== null;
	}

	/**
	 * Create all metric instruments
	 */
	private createMetrics(): void {
		if (!this.meter) return;

		// Counters
		this.agentInvocationsCounter = this.meter.createCounter(
			METRICS.AGENT_INVOCATIONS,
			{
				description: "Total number of agent invocations",
				unit: "1",
			} as MetricOptions,
		);

		this.toolExecutionsCounter = this.meter.createCounter(
			METRICS.TOOL_EXECUTIONS,
			{
				description: "Total number of tool executions",
				unit: "1",
			} as MetricOptions,
		);

		this.llmCallsCounter = this.meter.createCounter(METRICS.LLM_CALLS, {
			description: "Total number of LLM calls",
			unit: "1",
		} as MetricOptions);

		this.errorsCounter = this.meter.createCounter(METRICS.ERRORS, {
			description: "Total number of errors",
			unit: "1",
		} as MetricOptions);

		// Histograms
		this.agentDurationHistogram = this.meter.createHistogram(
			METRICS.AGENT_DURATION,
			{
				description: "Duration of agent invocations",
				unit: "ms",
			} as MetricOptions,
		);

		this.toolDurationHistogram = this.meter.createHistogram(
			METRICS.TOOL_DURATION,
			{
				description: "Duration of tool executions",
				unit: "ms",
			} as MetricOptions,
		);

		this.llmDurationHistogram = this.meter.createHistogram(
			METRICS.LLM_DURATION,
			{
				description: "Duration of LLM calls",
				unit: "ms",
			} as MetricOptions,
		);

		this.llmTokensHistogram = this.meter.createHistogram(METRICS.LLM_TOKENS, {
			description: "Total tokens used in LLM calls",
			unit: "1",
		} as MetricOptions);

		this.llmInputTokensHistogram = this.meter.createHistogram(
			METRICS.LLM_INPUT_TOKENS,
			{
				description: "Input tokens used in LLM calls",
				unit: "1",
			} as MetricOptions,
		);

		this.llmOutputTokensHistogram = this.meter.createHistogram(
			METRICS.LLM_OUTPUT_TOKENS,
			{
				description: "Output tokens generated by LLM calls",
				unit: "1",
			} as MetricOptions,
		);
	}

	/**
	 * Record an agent invocation
	 */
	recordAgentInvocation(dimensions: AgentMetricDimensions): void {
		if (!this.agentInvocationsCounter) return;

		const attributes: Record<string, string> = {
			"agent.name": dimensions.agentName,
			status: dimensions.status,
		};

		if (dimensions.environment) {
			attributes.environment = dimensions.environment;
		}

		this.agentInvocationsCounter.add(1, attributes);
	}

	/**
	 * Record agent execution duration
	 */
	recordAgentDuration(
		durationMs: number,
		dimensions: AgentMetricDimensions,
	): void {
		if (!this.agentDurationHistogram) return;

		const attributes: Record<string, string> = {
			"agent.name": dimensions.agentName,
			status: dimensions.status,
		};

		if (dimensions.environment) {
			attributes.environment = dimensions.environment;
		}

		this.agentDurationHistogram.record(durationMs, attributes);
	}

	/**
	 * Record a tool execution
	 */
	recordToolExecution(dimensions: ToolMetricDimensions): void {
		if (!this.toolExecutionsCounter) return;

		const attributes: Record<string, string> = {
			"tool.name": dimensions.toolName,
			status: dimensions.status,
		};

		if (dimensions.agentName) {
			attributes["agent.name"] = dimensions.agentName;
		}

		if (dimensions.environment) {
			attributes.environment = dimensions.environment;
		}

		this.toolExecutionsCounter.add(1, attributes);
	}

	/**
	 * Record tool execution duration
	 */
	recordToolDuration(
		durationMs: number,
		dimensions: ToolMetricDimensions,
	): void {
		if (!this.toolDurationHistogram) return;

		const attributes: Record<string, string> = {
			"tool.name": dimensions.toolName,
			status: dimensions.status,
		};

		if (dimensions.agentName) {
			attributes["agent.name"] = dimensions.agentName;
		}

		if (dimensions.environment) {
			attributes.environment = dimensions.environment;
		}

		this.toolDurationHistogram.record(durationMs, attributes);
	}

	/**
	 * Record an LLM call
	 */
	recordLlmCall(dimensions: LlmMetricDimensions): void {
		if (!this.llmCallsCounter) return;

		const attributes: Record<string, string> = {
			model: dimensions.model,
			status: dimensions.status,
		};

		if (dimensions.agentName) {
			attributes["agent.name"] = dimensions.agentName;
		}

		if (dimensions.environment) {
			attributes.environment = dimensions.environment;
		}

		this.llmCallsCounter.add(1, attributes);
	}

	/**
	 * Record LLM call duration
	 */
	recordLlmDuration(durationMs: number, dimensions: LlmMetricDimensions): void {
		if (!this.llmDurationHistogram) return;

		const attributes: Record<string, string> = {
			model: dimensions.model,
			status: dimensions.status,
		};

		if (dimensions.agentName) {
			attributes["agent.name"] = dimensions.agentName;
		}

		if (dimensions.environment) {
			attributes.environment = dimensions.environment;
		}

		this.llmDurationHistogram.record(durationMs, attributes);
	}

	/**
	 * Record LLM token usage
	 */
	recordLlmTokens(
		inputTokens: number,
		outputTokens: number,
		dimensions: LlmMetricDimensions,
	): void {
		if (
			!this.llmTokensHistogram ||
			!this.llmInputTokensHistogram ||
			!this.llmOutputTokensHistogram
		) {
			return;
		}

		const attributes: Record<string, string> = {
			model: dimensions.model,
			status: dimensions.status,
		};

		if (dimensions.agentName) {
			attributes["agent.name"] = dimensions.agentName;
		}

		if (dimensions.environment) {
			attributes.environment = dimensions.environment;
		}

		const totalTokens = inputTokens + outputTokens;

		this.llmTokensHistogram.record(totalTokens, attributes);
		this.llmInputTokensHistogram.record(inputTokens, attributes);
		this.llmOutputTokensHistogram.record(outputTokens, attributes);
	}

	/**
	 * Record an error
	 */
	recordError(errorType: "agent" | "tool" | "llm", context: string): void {
		if (!this.errorsCounter) return;

		this.errorsCounter.add(1, {
			error_type: errorType,
			context,
		});
	}
}

// Global singleton instance
export const metricsService = new MetricsService();
