services:
  adk-shade-agent-api:
    image: adk-shade-agent-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEAR_ACCOUNT_ID: ${NEAR_ACCOUNT_ID}
      NEAR_SEED_PHRASE: ${NEAR_SEED_PHRASE}
      API_CODEHASH: ${API_CODEHASH}
      APP_CODEHASH: ${APP_CODEHASH}
      NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
      NEAR_RPC_JSON: ${NEAR_RPC_JSON}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      ADK_DEBUG: ${ADK_DEBUG}
    platform: linux/amd64 # Explicitly set for TDX
    container_name: adk-shade-agent-api
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always